version: '3.8'
services:
  db:
    image: mysql:8.0.29
    environment:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${password}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        TZ: 'Asia/Tokyo'
    ports:
        - ${DB_PORT}:3306
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: "php-fpm"
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
    ports:
      - ${WEB_PORT}:80
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www
    # サービスの依存関係を指定（nginxをphpに依存させる）
    depends_on:
      - php
      
  node:
    image: node:14.18-alpine
    container_name: "node14.18-alpine"
    # コンテナ内の標準出力とホストの出力を設定：trueを指定
    tty: true
    ports:
      - 5173:5173
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src:/var/www
    # コンテナ起動後のカレントディレクトリを設定
    working_dir: /var/www
